name: CI Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout o código
        uses: actions/checkout@v4

      - name: Validar HTML
        uses: svenstaro/html5validator-action@v0.6.0
        with:
          path: .

      - name: Instalar csstree-validator
        run: npm install -g csstree-validator

      - name: Validar CSS
        run: csstree-validator "**/*.css"

      - name: Validar JavaScript
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          eslint_flags: '**/*.js'